// Generated by Verilator --design-db. Do not edit.
#include "xdd_api.h"
#include <cstring>

static const XddSignalInfo kSignals[] = {
    {"top.active_driver_tb.clk", "wire", 1, "testdata/fixtures/active_driver/active_driver_tb.sv", 35},
    {"top.active_driver_tb.rst_n", "wire", 1, "testdata/fixtures/active_driver/active_driver_tb.sv", 36},
    {"top.active_driver_tb.sel", "wire", 1, "testdata/fixtures/active_driver/active_driver_tb.sv", 37},
    {"top.active_driver_tb.mode", "wire", 2, "testdata/fixtures/active_driver/active_driver_tb.sv", 38},
    {"top.active_driver_tb.data_a", "wire", 8, "testdata/fixtures/active_driver/active_driver_tb.sv", 39},
    {"top.active_driver_tb.data_b", "wire", 8, "testdata/fixtures/active_driver/active_driver_tb.sv", 40},
    {"top.active_driver_tb.q", "wire", 8, "testdata/fixtures/active_driver/active_driver_tb.sv", 41},
    {"top.active_driver_tb.comb_q", "wire", 8, "testdata/fixtures/active_driver/active_driver_tb.sv", 42},
    {"top.active_driver_tb.u_dut.clk", "port", 1, "testdata/fixtures/active_driver/active_driver_tb.sv", 4},
    {"top.active_driver_tb.u_dut.rst_n", "port", 1, "testdata/fixtures/active_driver/active_driver_tb.sv", 5},
    {"top.active_driver_tb.u_dut.sel", "port", 1, "testdata/fixtures/active_driver/active_driver_tb.sv", 6},
    {"top.active_driver_tb.u_dut.mode", "port", 2, "testdata/fixtures/active_driver/active_driver_tb.sv", 7},
    {"top.active_driver_tb.u_dut.data_a", "port", 8, "testdata/fixtures/active_driver/active_driver_tb.sv", 8},
    {"top.active_driver_tb.u_dut.data_b", "port", 8, "testdata/fixtures/active_driver/active_driver_tb.sv", 9},
    {"top.active_driver_tb.u_dut.q", "port", 8, "testdata/fixtures/active_driver/active_driver_tb.sv", 10},
    {"top.active_driver_tb.u_dut.comb_q", "port", 8, "testdata/fixtures/active_driver/active_driver_tb.sv", 11},
};
static const int kSignalCount = 16;

static const int kSignalDirections[] = {0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2};

static const XddNameEntry kNameIndex[] = {
    {"top.active_driver_tb.clk", 0},
    {"top.active_driver_tb.comb_q", 7},
    {"top.active_driver_tb.data_a", 4},
    {"top.active_driver_tb.data_b", 5},
    {"top.active_driver_tb.mode", 3},
    {"top.active_driver_tb.q", 6},
    {"top.active_driver_tb.rst_n", 1},
    {"top.active_driver_tb.sel", 2},
    {"top.active_driver_tb.u_dut.clk", 8},
    {"top.active_driver_tb.u_dut.comb_q", 15},
    {"top.active_driver_tb.u_dut.data_a", 12},
    {"top.active_driver_tb.u_dut.data_b", 13},
    {"top.active_driver_tb.u_dut.mode", 11},
    {"top.active_driver_tb.u_dut.q", 14},
    {"top.active_driver_tb.u_dut.rst_n", 9},
    {"top.active_driver_tb.u_dut.sel", 10},
};
static const int kNameIndexCount = 16;

static const XddDriverRec kDrivers[] = {
    {0, -1, "proc_assign", "statement", "testdata/fixtures/active_driver/active_driver_tb.sv", 56},
    {1, -1, "proc_assign", "statement", "testdata/fixtures/active_driver/active_driver_tb.sv", 61},
    {1, -1, "proc_assign", "statement", "testdata/fixtures/active_driver/active_driver_tb.sv", 68},
    {2, -1, "proc_assign", "statement", "testdata/fixtures/active_driver/active_driver_tb.sv", 62},
    {2, -1, "proc_assign", "statement", "testdata/fixtures/active_driver/active_driver_tb.sv", 69},
    {2, -1, "proc_assign", "statement", "testdata/fixtures/active_driver/active_driver_tb.sv", 72},
    {2, -1, "proc_assign", "statement", "testdata/fixtures/active_driver/active_driver_tb.sv", 77},
    {3, -1, "proc_assign", "statement", "testdata/fixtures/active_driver/active_driver_tb.sv", 63},
    {3, -1, "proc_assign", "statement", "testdata/fixtures/active_driver/active_driver_tb.sv", 73},
    {3, -1, "proc_assign", "statement", "testdata/fixtures/active_driver/active_driver_tb.sv", 78},
    {3, -1, "proc_assign", "statement", "testdata/fixtures/active_driver/active_driver_tb.sv", 88},
    {4, -1, "proc_assign", "statement", "testdata/fixtures/active_driver/active_driver_tb.sv", 64},
    {4, -1, "proc_assign", "statement", "testdata/fixtures/active_driver/active_driver_tb.sv", 79},
    {5, -1, "proc_assign", "statement", "testdata/fixtures/active_driver/active_driver_tb.sv", 65},
    {5, -1, "proc_assign", "statement", "testdata/fixtures/active_driver/active_driver_tb.sv", 74},
    {6, 14, "cont_assign", "rhs", "testdata/fixtures/active_driver/active_driver_tb.sv", 10},
    {7, 14, "proc_assign", "rhs", "testdata/fixtures/active_driver/active_driver_tb.sv", 25},
    {7, 3, "proc_assign", "control", "testdata/fixtures/active_driver/active_driver_tb.sv", 25},
    {7, 4, "proc_assign", "rhs", "testdata/fixtures/active_driver/active_driver_tb.sv", 26},
    {7, 3, "proc_assign", "control", "testdata/fixtures/active_driver/active_driver_tb.sv", 26},
    {7, 5, "proc_assign", "rhs", "testdata/fixtures/active_driver/active_driver_tb.sv", 27},
    {7, 3, "proc_assign", "control", "testdata/fixtures/active_driver/active_driver_tb.sv", 27},
    {7, 3, "proc_assign", "control", "testdata/fixtures/active_driver/active_driver_tb.sv", 28},
    {8, 0, "cont_assign", "rhs", "testdata/fixtures/active_driver/active_driver_tb.sv", 4},
    {9, 1, "cont_assign", "rhs", "testdata/fixtures/active_driver/active_driver_tb.sv", 5},
    {10, 2, "cont_assign", "rhs", "testdata/fixtures/active_driver/active_driver_tb.sv", 6},
    {11, 3, "cont_assign", "rhs", "testdata/fixtures/active_driver/active_driver_tb.sv", 7},
    {12, 4, "cont_assign", "rhs", "testdata/fixtures/active_driver/active_driver_tb.sv", 8},
    {13, 5, "cont_assign", "rhs", "testdata/fixtures/active_driver/active_driver_tb.sv", 9},
    {14, -1, "force", "statement", "testdata/fixtures/active_driver/active_driver_tb.sv", 82},
    {14, 4, "nba", "rhs", "testdata/fixtures/active_driver/active_driver_tb.sv", 18},
    {14, 1, "nba", "control", "testdata/fixtures/active_driver/active_driver_tb.sv", 18},
    {14, 2, "nba", "control", "testdata/fixtures/active_driver/active_driver_tb.sv", 18},
    {14, 0, "nba", "event_posedge", "testdata/fixtures/active_driver/active_driver_tb.sv", 18},
    {14, 1, "nba", "event_negedge", "testdata/fixtures/active_driver/active_driver_tb.sv", 18},
    {14, 5, "nba", "rhs", "testdata/fixtures/active_driver/active_driver_tb.sv", 20},
    {14, 1, "nba", "control", "testdata/fixtures/active_driver/active_driver_tb.sv", 20},
    {14, 2, "nba", "control", "testdata/fixtures/active_driver/active_driver_tb.sv", 20},
    {14, 0, "nba", "event_posedge", "testdata/fixtures/active_driver/active_driver_tb.sv", 20},
    {14, 1, "nba", "event_negedge", "testdata/fixtures/active_driver/active_driver_tb.sv", 20},
    {14, 1, "nba", "control", "testdata/fixtures/active_driver/active_driver_tb.sv", 16},
    {14, 0, "nba", "event_posedge", "testdata/fixtures/active_driver/active_driver_tb.sv", 16},
    {14, 1, "nba", "event_negedge", "testdata/fixtures/active_driver/active_driver_tb.sv", 16},
    {15, 7, "cont_assign", "rhs", "testdata/fixtures/active_driver/active_driver_tb.sv", 11},
};
static const int kDriverCount = 44;
static const char* const kDriverPredicates[] = {
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "((top.active_driver_tb.mode) === (2'h0))",
    "((top.active_driver_tb.mode) === (2'h0))",
    "((top.active_driver_tb.mode) === (2'h1))",
    "((top.active_driver_tb.mode) === (2'h1))",
    "((top.active_driver_tb.mode) === (2'h2))",
    "((top.active_driver_tb.mode) === (2'h2))",
    "!(((top.active_driver_tb.mode) === (2'h0)) || ((top.active_driver_tb.mode) === (2'h1)) || ((top.active_driver_tb.mode) === (2'h2)))",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "(top.active_driver_tb.rst_n) && (top.active_driver_tb.sel)",
    "(top.active_driver_tb.rst_n) && (top.active_driver_tb.sel)",
    "(top.active_driver_tb.rst_n) && (top.active_driver_tb.sel)",
    "(top.active_driver_tb.rst_n) && (top.active_driver_tb.sel)",
    "(top.active_driver_tb.rst_n) && (top.active_driver_tb.sel)",
    "(top.active_driver_tb.rst_n) && !(top.active_driver_tb.sel)",
    "(top.active_driver_tb.rst_n) && !(top.active_driver_tb.sel)",
    "(top.active_driver_tb.rst_n) && !(top.active_driver_tb.sel)",
    "(top.active_driver_tb.rst_n) && !(top.active_driver_tb.sel)",
    "(top.active_driver_tb.rst_n) && !(top.active_driver_tb.sel)",
    "!(top.active_driver_tb.rst_n)",
    "!(top.active_driver_tb.rst_n)",
    "!(top.active_driver_tb.rst_n)",
    "1",
};
static const int kDriverStart[] = {0, 1, 3, 7, 11, 13, 15, 16, 23, 24, 25, 26, 27, 28, 29, 43};

static const XddPortConnectionRec kPortConnections[] = {
    {8, 0, "port_boundary"},
    {9, 1, "port_boundary"},
    {10, 2, "port_boundary"},
    {11, 3, "port_boundary"},
    {12, 4, "port_boundary"},
    {13, 5, "port_boundary"},
    {14, 6, "port_boundary"},
    {15, 7, "port_boundary"},
};
static const int kPortConnectionCount = 8;
static const int kPortConnectionStart[] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7};

static const XddLoadRec kLoads[] = {
    {0, 8, "rhs_use", "testdata/fixtures/active_driver/active_driver_tb.sv", 4},
    {0, 0, "rhs_use", "testdata/fixtures/active_driver/active_driver_tb.sv", 57},
    {1, 9, "rhs_use", "testdata/fixtures/active_driver/active_driver_tb.sv", 5},
    {1, 14, "control_use", "testdata/fixtures/active_driver/active_driver_tb.sv", 18},
    {1, 14, "control_use", "testdata/fixtures/active_driver/active_driver_tb.sv", 20},
    {1, 14, "control_use", "testdata/fixtures/active_driver/active_driver_tb.sv", 16},
    {2, 10, "rhs_use", "testdata/fixtures/active_driver/active_driver_tb.sv", 6},
    {2, 14, "control_use", "testdata/fixtures/active_driver/active_driver_tb.sv", 18},
    {2, 14, "control_use", "testdata/fixtures/active_driver/active_driver_tb.sv", 20},
    {3, 11, "rhs_use", "testdata/fixtures/active_driver/active_driver_tb.sv", 7},
    {3, 7, "control_use", "testdata/fixtures/active_driver/active_driver_tb.sv", 25},
    {3, 7, "control_use", "testdata/fixtures/active_driver/active_driver_tb.sv", 26},
    {3, 7, "control_use", "testdata/fixtures/active_driver/active_driver_tb.sv", 27},
    {3, 7, "control_use", "testdata/fixtures/active_driver/active_driver_tb.sv", 28},
    {4, 12, "rhs_use", "testdata/fixtures/active_driver/active_driver_tb.sv", 8},
    {4, 14, "rhs_use", "testdata/fixtures/active_driver/active_driver_tb.sv", 18},
    {4, 7, "rhs_use", "testdata/fixtures/active_driver/active_driver_tb.sv", 26},
    {5, 13, "rhs_use", "testdata/fixtures/active_driver/active_driver_tb.sv", 9},
    {5, 14, "rhs_use", "testdata/fixtures/active_driver/active_driver_tb.sv", 20},
    {5, 7, "rhs_use", "testdata/fixtures/active_driver/active_driver_tb.sv", 27},
    {7, 15, "rhs_use", "testdata/fixtures/active_driver/active_driver_tb.sv", 11},
    {14, 6, "rhs_use", "testdata/fixtures/active_driver/active_driver_tb.sv", 10},
    {14, 7, "rhs_use", "testdata/fixtures/active_driver/active_driver_tb.sv", 25},
};
static const int kLoadCount = 23;
static const int kLoadStart[] = {0, 2, 6, 9, 14, 17, 20, 20, 21, 21, 21, 21, 21, 21, 21, 23};


extern "C" {

int xdd_abi_version(void) { return XDD_ABI_VERSION; }
uint64_t xdd_capabilities(void) {
    return XDD_CAP_SIGNAL_DIRECTION | XDD_CAP_PORT_CONNECTIONS
           | XDD_CAP_DRIVER_DEPENDENCY_ROLE | XDD_CAP_DRIVER_PREDICATE;
}

XddDb* xdd_init(void) { return reinterpret_cast<XddDb*>(1); }
void xdd_close(XddDb*) {}

int xdd_signal_count(XddDb*) { return kSignalCount; }

XddSignal xdd_resolve(XddDb*, const char* name) {
    int lo = 0, hi = kNameIndexCount - 1;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        int cmp = std::strcmp(name, kNameIndex[mid].name);
        if (cmp == 0) return kNameIndex[mid].index;
        if (cmp < 0) hi = mid - 1;
        else lo = mid + 1;
    }
    return -1;
}

const char* xdd_signal_name(XddDb*, int idx) {
    return (idx >= 0 && idx < kSignalCount) ? kSignals[idx].name : nullptr;
}
int xdd_signal_width(XddDb*, int idx) {
    return (idx >= 0 && idx < kSignalCount) ? kSignals[idx].width : 0;
}
const char* xdd_signal_type(XddDb*, int idx) {
    return (idx >= 0 && idx < kSignalCount) ? kSignals[idx].type : nullptr;
}
const char* xdd_signal_file(XddDb*, int idx) {
    return (idx >= 0 && idx < kSignalCount) ? kSignals[idx].file : nullptr;
}
int xdd_signal_line(XddDb*, int idx) {
    return (idx >= 0 && idx < kSignalCount) ? kSignals[idx].line : 0;
}
int xdd_signal_direction(XddDb*, int idx) {
    return (idx >= 0 && idx < kSignalCount) ? kSignalDirections[idx] : 0;
}

int xdd_port_connection_count(XddDb*, int idx) {
    if (idx < 0 || idx >= kSignalCount) return 0;
    int e = (idx + 1 < kSignalCount) ? kPortConnectionStart[idx + 1]
                                     : kPortConnectionCount;
    return e - kPortConnectionStart[idx];
}

void xdd_port_connection(XddDb*, int idx, int i,
                         int* connected_signal, const char** kind) {
    *connected_signal = -1;
    *kind = nullptr;
    if (idx < 0 || idx >= kSignalCount) return;
    int s = kPortConnectionStart[idx];
    int e = (idx + 1 < kSignalCount) ? kPortConnectionStart[idx + 1]
                                     : kPortConnectionCount;
    if (i < 0 || i >= (e - s)) return;
    const XddPortConnectionRec& connection = kPortConnections[s + i];
    *connected_signal = connection.connected_signal;
    *kind = connection.kind;
}

int xdd_trace_driver_count(XddDb*, int idx) {
    if (idx < 0 || idx >= kSignalCount) return 0;
    int e = (idx + 1 < kSignalCount) ? kDriverStart[idx + 1] : kDriverCount;
    return e - kDriverStart[idx];
}

void xdd_trace_driver(XddDb*, int idx, int i,
                      int* src_signal, const char** kind,
                      const char** file, int* line) {
    *src_signal = -1; *kind = nullptr; *file = nullptr; *line = 0;
    if (idx < 0 || idx >= kSignalCount) return;
    int s = kDriverStart[idx];
    int e = (idx + 1 < kSignalCount) ? kDriverStart[idx + 1] : kDriverCount;
    if (i < 0 || i >= (e - s)) return;
    const XddDriverRec& d = kDrivers[s + i];
    *src_signal = d.src_signal; *kind = d.kind; *file = d.file; *line = d.line;
}

const char* xdd_trace_driver_role(XddDb*, int idx, int i) {
    if (idx < 0 || idx >= kSignalCount) return nullptr;
    int s = kDriverStart[idx];
    int e = (idx + 1 < kSignalCount) ? kDriverStart[idx + 1] : kDriverCount;
    if (i < 0 || i >= (e - s)) return nullptr;
    return kDrivers[s + i].role;
}

const char* xdd_trace_driver_predicate(XddDb*, int idx, int i) {
    if (idx < 0 || idx >= kSignalCount) return nullptr;
    int s = kDriverStart[idx];
    int e = (idx + 1 < kSignalCount) ? kDriverStart[idx + 1] : kDriverCount;
    if (i < 0 || i >= (e - s)) return nullptr;
    return kDriverPredicates[s + i];
}

int xdd_trace_load_count(XddDb*, int idx) {
    if (idx < 0 || idx >= kSignalCount) return 0;
    int e = (idx + 1 < kSignalCount) ? kLoadStart[idx + 1] : kLoadCount;
    return e - kLoadStart[idx];
}

void xdd_trace_load(XddDb*, int idx, int i,
                    int* consumer, const char** kind,
                    const char** file, int* line) {
    *consumer = -1; *kind = nullptr; *file = nullptr; *line = 0;
    if (idx < 0 || idx >= kSignalCount) return;
    int s = kLoadStart[idx];
    int e = (idx + 1 < kSignalCount) ? kLoadStart[idx + 1] : kLoadCount;
    if (i < 0 || i >= (e - s)) return;
    const XddLoadRec& l = kLoads[s + i];
    *consumer = l.consumer; *kind = l.kind; *file = l.file; *line = l.line;
}

}  // extern "C"
