// Generated by Verilator --design-db. Do not edit.
#include "xdd_api.h"
#include <cstring>

static const XddSignalInfo kSignals[] = {
    {"top.clk", "port", 1, "counter_top.sv", 2},
    {"top.reset", "port", 1, "counter_top.sv", 3},
    {"top.count", "port", 8, "counter_top.sv", 4},
    {"top.overflow", "port", 1, "counter_top.sv", 5},
    {"top.counter_top.clk", "wire", 1, "counter_top.sv", 2},
    {"top.counter_top.reset", "wire", 1, "counter_top.sv", 3},
    {"top.counter_top.count", "wire", 8, "counter_top.sv", 4},
    {"top.counter_top.overflow", "wire", 1, "counter_top.sv", 5},
};
static const int kSignalCount = 8;

static const XddNameEntry kNameIndex[] = {
    {"top.clk", 0},
    {"top.count", 2},
    {"top.counter_top.clk", 4},
    {"top.counter_top.count", 6},
    {"top.counter_top.overflow", 7},
    {"top.counter_top.reset", 5},
    {"top.overflow", 3},
    {"top.reset", 1},
};
static const int kNameIndexCount = 8;

static const XddDriverRec kDrivers[] = {
    {2, 1, "nba", "counter_top.sv", 9},
    {2, 1, "nba", "counter_top.sv", 12},
    {3, 1, "nba", "counter_top.sv", 10},
    {3, 2, "nba", "counter_top.sv", 13},
    {3, 1, "nba", "counter_top.sv", 13},
    {4, 0, "cont_assign", "counter_top.sv", 2},
    {5, 1, "cont_assign", "counter_top.sv", 3},
    {6, 2, "cont_assign", "counter_top.sv", 4},
    {7, 3, "cont_assign", "counter_top.sv", 5},
};
static const int kDriverCount = 9;
static const int kDriverStart[] = {0, 0, 0, 2, 5, 6, 7, 8};

static const XddLoadRec kLoads[] = {
    {0, 4, "rhs_use", "counter_top.sv", 2},
    {1, 5, "rhs_use", "counter_top.sv", 3},
    {1, 2, "rhs_use", "counter_top.sv", 9},
    {1, 3, "rhs_use", "counter_top.sv", 10},
    {1, 2, "rhs_use", "counter_top.sv", 12},
    {1, 3, "rhs_use", "counter_top.sv", 13},
    {2, 6, "rhs_use", "counter_top.sv", 4},
    {2, 2, "rhs_use", "counter_top.sv", 12},
    {2, 3, "rhs_use", "counter_top.sv", 13},
    {3, 7, "rhs_use", "counter_top.sv", 5},
};
static const int kLoadCount = 10;
static const int kLoadStart[] = {0, 1, 6, 9, 10, 10, 10, 10};


extern "C" {

XddDb* xdd_init(void) { return reinterpret_cast<XddDb*>(1); }
void xdd_close(XddDb*) {}

int xdd_signal_count(XddDb*) { return kSignalCount; }

XddSignal xdd_resolve(XddDb*, const char* name) {
    int lo = 0, hi = kNameIndexCount - 1;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        int cmp = std::strcmp(name, kNameIndex[mid].name);
        if (cmp == 0) return kNameIndex[mid].index;
        if (cmp < 0) hi = mid - 1;
        else lo = mid + 1;
    }
    return -1;
}

const char* xdd_signal_name(XddDb*, int idx) {
    return (idx >= 0 && idx < kSignalCount) ? kSignals[idx].name : nullptr;
}
int xdd_signal_width(XddDb*, int idx) {
    return (idx >= 0 && idx < kSignalCount) ? kSignals[idx].width : 0;
}
const char* xdd_signal_type(XddDb*, int idx) {
    return (idx >= 0 && idx < kSignalCount) ? kSignals[idx].type : nullptr;
}
const char* xdd_signal_file(XddDb*, int idx) {
    return (idx >= 0 && idx < kSignalCount) ? kSignals[idx].file : nullptr;
}
int xdd_signal_line(XddDb*, int idx) {
    return (idx >= 0 && idx < kSignalCount) ? kSignals[idx].line : 0;
}

int xdd_trace_driver_count(XddDb*, int idx) {
    if (idx < 0 || idx >= kSignalCount) return 0;
    int e = (idx + 1 < kSignalCount) ? kDriverStart[idx + 1] : kDriverCount;
    return e - kDriverStart[idx];
}

void xdd_trace_driver(XddDb*, int idx, int i,
                      int* src_signal, const char** kind,
                      const char** file, int* line) {
    *src_signal = -1; *kind = nullptr; *file = nullptr; *line = 0;
    if (idx < 0 || idx >= kSignalCount) return;
    int s = kDriverStart[idx];
    int e = (idx + 1 < kSignalCount) ? kDriverStart[idx + 1] : kDriverCount;
    if (i < 0 || i >= (e - s)) return;
    const XddDriverRec& d = kDrivers[s + i];
    *src_signal = d.src_signal; *kind = d.kind; *file = d.file; *line = d.line;
}

int xdd_trace_load_count(XddDb*, int idx) {
    if (idx < 0 || idx >= kSignalCount) return 0;
    int e = (idx + 1 < kSignalCount) ? kLoadStart[idx + 1] : kLoadCount;
    return e - kLoadStart[idx];
}

void xdd_trace_load(XddDb*, int idx, int i,
                    int* consumer, const char** kind,
                    const char** file, int* line) {
    *consumer = -1; *kind = nullptr; *file = nullptr; *line = 0;
    if (idx < 0 || idx >= kSignalCount) return;
    int s = kLoadStart[idx];
    int e = (idx + 1 < kSignalCount) ? kLoadStart[idx + 1] : kLoadCount;
    if (i < 0 || i >= (e - s)) return;
    const XddLoadRec& l = kLoads[s + i];
    *consumer = l.consumer; *kind = l.kind; *file = l.file; *line = l.line;
}

}  // extern "C"
