// Generated by Verilator --design-db. Do not edit.
#include "xdd_api.h"
#include <cstring>

static const XddSignalInfo kSignals[] = {
    {"top.if_root_tb.clk", "wire", 1, "testdata/fixtures/interface_port_root/if_root_tb.sv", 41},
    {"top.if_root_tb.rst_n", "wire", 1, "testdata/fixtures/interface_port_root/if_root_tb.sv", 42},
    {"top.if_root_tb.sel", "wire", 1, "testdata/fixtures/interface_port_root/if_root_tb.sv", 43},
    {"top.if_root_tb.a", "wire", 8, "testdata/fixtures/interface_port_root/if_root_tb.sv", 44},
    {"top.if_root_tb.b", "wire", 8, "testdata/fixtures/interface_port_root/if_root_tb.sv", 45},
    {"top.if_root_tb.observed_q", "wire", 8, "testdata/fixtures/interface_port_root/if_root_tb.sv", 46},
    {"top.if_root_tb.link.if_root_tb.link__viftop", "wire", 0, "testdata/fixtures/interface_port_root/if_root_tb.sv", 48},
    {"top.if_root_tb.u_sink.rst_n", "port", 1, "testdata/fixtures/interface_port_root/if_root_tb.sv", 28},
    {"top.if_root_tb.u_sink.bus", "port", 0, "testdata/fixtures/interface_port_root/if_root_tb.sv", 29},
    {"top.if_root_tb.u_sink.observed_q", "port", 8, "testdata/fixtures/interface_port_root/if_root_tb.sv", 30},
    {"top.if_root_tb.u_src.rst_n", "port", 1, "testdata/fixtures/interface_port_root/if_root_tb.sv", 11},
    {"top.if_root_tb.u_src.sel", "port", 1, "testdata/fixtures/interface_port_root/if_root_tb.sv", 12},
    {"top.if_root_tb.u_src.a", "port", 8, "testdata/fixtures/interface_port_root/if_root_tb.sv", 13},
    {"top.if_root_tb.u_src.b", "port", 8, "testdata/fixtures/interface_port_root/if_root_tb.sv", 14},
    {"top.if_root_tb.u_src.bus", "port", 0, "testdata/fixtures/interface_port_root/if_root_tb.sv", 15},
    {"top.if_root_tb.link.clk", "port", 1, "testdata/fixtures/interface_port_root/if_root_tb.sv", 3},
    {"top.if_root_tb.link.data", "wire", 8, "testdata/fixtures/interface_port_root/if_root_tb.sv", 4},
    {"top.if_root_tb.u_sink.bus.data", "port", 8, "testdata/fixtures/interface_port_root/if_root_tb.sv", 7},
    {"top.if_root_tb.u_sink.bus.clk", "port", 1, "testdata/fixtures/interface_port_root/if_root_tb.sv", 7},
    {"top.if_root_tb.u_src.bus.data", "port", 8, "testdata/fixtures/interface_port_root/if_root_tb.sv", 6},
    {"top.if_root_tb.u_src.bus.clk", "port", 1, "testdata/fixtures/interface_port_root/if_root_tb.sv", 6},
};
static const int kSignalCount = 21;

static const int kSignalDirections[] = {0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 1, 1, 1, 1, 1, 1, 0, 1, 1, 2, 1};

static const XddNameEntry kNameIndex[] = {
    {"top.if_root_tb.a", 3},
    {"top.if_root_tb.b", 4},
    {"top.if_root_tb.clk", 0},
    {"top.if_root_tb.link.clk", 15},
    {"top.if_root_tb.link.data", 16},
    {"top.if_root_tb.link.if_root_tb.link__viftop", 6},
    {"top.if_root_tb.observed_q", 5},
    {"top.if_root_tb.rst_n", 1},
    {"top.if_root_tb.sel", 2},
    {"top.if_root_tb.u_sink.bus", 8},
    {"top.if_root_tb.u_sink.bus.clk", 18},
    {"top.if_root_tb.u_sink.bus.data", 17},
    {"top.if_root_tb.u_sink.observed_q", 9},
    {"top.if_root_tb.u_sink.rst_n", 7},
    {"top.if_root_tb.u_src.a", 12},
    {"top.if_root_tb.u_src.b", 13},
    {"top.if_root_tb.u_src.bus", 14},
    {"top.if_root_tb.u_src.bus.clk", 20},
    {"top.if_root_tb.u_src.bus.data", 19},
    {"top.if_root_tb.u_src.rst_n", 10},
    {"top.if_root_tb.u_src.sel", 11},
};
static const int kNameIndexCount = 21;

static const XddDriverRec kDrivers[] = {
    {0, -1, "proc_assign", "statement", "testdata/fixtures/interface_port_root/if_root_tb.sv", 65},
    {1, -1, "proc_assign", "statement", "testdata/fixtures/interface_port_root/if_root_tb.sv", 70},
    {1, -1, "proc_assign", "statement", "testdata/fixtures/interface_port_root/if_root_tb.sv", 76},
    {2, -1, "proc_assign", "statement", "testdata/fixtures/interface_port_root/if_root_tb.sv", 71},
    {2, -1, "proc_assign", "statement", "testdata/fixtures/interface_port_root/if_root_tb.sv", 77},
    {2, -1, "proc_assign", "statement", "testdata/fixtures/interface_port_root/if_root_tb.sv", 80},
    {3, -1, "proc_assign", "statement", "testdata/fixtures/interface_port_root/if_root_tb.sv", 72},
    {4, -1, "proc_assign", "statement", "testdata/fixtures/interface_port_root/if_root_tb.sv", 73},
    {5, 16, "nba", "rhs", "testdata/fixtures/interface_port_root/if_root_tb.sv", 36},
    {5, 1, "nba", "control", "testdata/fixtures/interface_port_root/if_root_tb.sv", 36},
    {5, 15, "nba", "event_posedge", "testdata/fixtures/interface_port_root/if_root_tb.sv", 36},
    {5, 1, "nba", "event_negedge", "testdata/fixtures/interface_port_root/if_root_tb.sv", 36},
    {5, 1, "nba", "control", "testdata/fixtures/interface_port_root/if_root_tb.sv", 34},
    {5, 15, "nba", "event_posedge", "testdata/fixtures/interface_port_root/if_root_tb.sv", 34},
    {5, 1, "nba", "event_negedge", "testdata/fixtures/interface_port_root/if_root_tb.sv", 34},
    {7, 1, "cont_assign", "rhs", "testdata/fixtures/interface_port_root/if_root_tb.sv", 28},
    {9, 5, "cont_assign", "rhs", "testdata/fixtures/interface_port_root/if_root_tb.sv", 30},
    {10, 1, "cont_assign", "rhs", "testdata/fixtures/interface_port_root/if_root_tb.sv", 11},
    {11, 2, "cont_assign", "rhs", "testdata/fixtures/interface_port_root/if_root_tb.sv", 12},
    {12, 3, "cont_assign", "rhs", "testdata/fixtures/interface_port_root/if_root_tb.sv", 13},
    {13, 4, "cont_assign", "rhs", "testdata/fixtures/interface_port_root/if_root_tb.sv", 14},
    {15, 0, "cont_assign", "rhs", "testdata/fixtures/interface_port_root/if_root_tb.sv", 48},
    {16, 3, "nba", "rhs", "testdata/fixtures/interface_port_root/if_root_tb.sv", 21},
    {16, 1, "nba", "control", "testdata/fixtures/interface_port_root/if_root_tb.sv", 21},
    {16, 2, "nba", "control", "testdata/fixtures/interface_port_root/if_root_tb.sv", 21},
    {16, 15, "nba", "event_posedge", "testdata/fixtures/interface_port_root/if_root_tb.sv", 21},
    {16, 1, "nba", "event_negedge", "testdata/fixtures/interface_port_root/if_root_tb.sv", 21},
    {16, 4, "nba", "rhs", "testdata/fixtures/interface_port_root/if_root_tb.sv", 23},
    {16, 1, "nba", "control", "testdata/fixtures/interface_port_root/if_root_tb.sv", 23},
    {16, 2, "nba", "control", "testdata/fixtures/interface_port_root/if_root_tb.sv", 23},
    {16, 15, "nba", "event_posedge", "testdata/fixtures/interface_port_root/if_root_tb.sv", 23},
    {16, 1, "nba", "event_negedge", "testdata/fixtures/interface_port_root/if_root_tb.sv", 23},
    {16, 1, "nba", "control", "testdata/fixtures/interface_port_root/if_root_tb.sv", 19},
    {16, 15, "nba", "event_posedge", "testdata/fixtures/interface_port_root/if_root_tb.sv", 19},
    {16, 1, "nba", "event_negedge", "testdata/fixtures/interface_port_root/if_root_tb.sv", 19},
    {19, 3, "nba", "rhs", "testdata/fixtures/interface_port_root/if_root_tb.sv", 21},
    {19, 1, "nba", "control", "testdata/fixtures/interface_port_root/if_root_tb.sv", 21},
    {19, 2, "nba", "control", "testdata/fixtures/interface_port_root/if_root_tb.sv", 21},
    {19, 15, "nba", "event_posedge", "testdata/fixtures/interface_port_root/if_root_tb.sv", 21},
    {19, 4, "nba", "rhs", "testdata/fixtures/interface_port_root/if_root_tb.sv", 23},
    {19, 1, "nba", "control", "testdata/fixtures/interface_port_root/if_root_tb.sv", 23},
    {19, 2, "nba", "control", "testdata/fixtures/interface_port_root/if_root_tb.sv", 23},
    {19, 15, "nba", "event_posedge", "testdata/fixtures/interface_port_root/if_root_tb.sv", 23},
    {19, 1, "nba", "control", "testdata/fixtures/interface_port_root/if_root_tb.sv", 19},
    {19, 15, "nba", "event_posedge", "testdata/fixtures/interface_port_root/if_root_tb.sv", 19},
};
static const int kDriverCount = 45;
static const char* const kDriverPredicates[] = {
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "(top.if_root_tb.rst_n)",
    "(top.if_root_tb.rst_n)",
    "(top.if_root_tb.rst_n)",
    "(top.if_root_tb.rst_n)",
    "!(top.if_root_tb.rst_n)",
    "!(top.if_root_tb.rst_n)",
    "!(top.if_root_tb.rst_n)",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "(top.if_root_tb.rst_n) && (top.if_root_tb.sel)",
    "(top.if_root_tb.rst_n) && (top.if_root_tb.sel)",
    "(top.if_root_tb.rst_n) && (top.if_root_tb.sel)",
    "(top.if_root_tb.rst_n) && (top.if_root_tb.sel)",
    "(top.if_root_tb.rst_n) && (top.if_root_tb.sel)",
    "(top.if_root_tb.rst_n) && !(top.if_root_tb.sel)",
    "(top.if_root_tb.rst_n) && !(top.if_root_tb.sel)",
    "(top.if_root_tb.rst_n) && !(top.if_root_tb.sel)",
    "(top.if_root_tb.rst_n) && !(top.if_root_tb.sel)",
    "(top.if_root_tb.rst_n) && !(top.if_root_tb.sel)",
    "!(top.if_root_tb.rst_n)",
    "!(top.if_root_tb.rst_n)",
    "!(top.if_root_tb.rst_n)",
    "(top.if_root_tb.rst_n) && (top.if_root_tb.sel)",
    "(top.if_root_tb.rst_n) && (top.if_root_tb.sel)",
    "(top.if_root_tb.rst_n) && (top.if_root_tb.sel)",
    "(top.if_root_tb.rst_n) && (top.if_root_tb.sel)",
    "(top.if_root_tb.rst_n) && !(top.if_root_tb.sel)",
    "(top.if_root_tb.rst_n) && !(top.if_root_tb.sel)",
    "(top.if_root_tb.rst_n) && !(top.if_root_tb.sel)",
    "(top.if_root_tb.rst_n) && !(top.if_root_tb.sel)",
    "!(top.if_root_tb.rst_n)",
    "!(top.if_root_tb.rst_n)",
};
static const int kDriverStart[] = {0, 1, 3, 6, 7, 8, 15, 15, 16, 16, 17, 18, 19, 20, 21, 21, 22, 35, 35, 35, 45};

static const XddPortConnectionRec kPortConnections[] = {
    {7, 1, "port_boundary"},
    {9, 5, "port_boundary"},
    {10, 1, "port_boundary"},
    {11, 2, "port_boundary"},
    {12, 3, "port_boundary"},
    {13, 4, "port_boundary"},
    {15, 0, "port_boundary"},
    {17, 16, "interface_modport_member"},
    {18, 15, "interface_modport_member"},
    {19, 16, "interface_modport_member"},
    {20, 15, "interface_modport_member"},
};
static const int kPortConnectionCount = 11;
static const int kPortConnectionStart[] = {0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 3, 4, 5, 6, 6, 7, 7, 8, 9, 10};

static const XddLoadRec kLoads[] = {
    {0, 15, "rhs_use", "testdata/fixtures/interface_port_root/if_root_tb.sv", 48},
    {0, 0, "rhs_use", "testdata/fixtures/interface_port_root/if_root_tb.sv", 66},
    {1, 7, "rhs_use", "testdata/fixtures/interface_port_root/if_root_tb.sv", 28},
    {1, 10, "rhs_use", "testdata/fixtures/interface_port_root/if_root_tb.sv", 11},
    {1, 5, "control_use", "testdata/fixtures/interface_port_root/if_root_tb.sv", 36},
    {1, 5, "control_use", "testdata/fixtures/interface_port_root/if_root_tb.sv", 34},
    {1, 16, "control_use", "testdata/fixtures/interface_port_root/if_root_tb.sv", 21},
    {1, 16, "control_use", "testdata/fixtures/interface_port_root/if_root_tb.sv", 23},
    {1, 16, "control_use", "testdata/fixtures/interface_port_root/if_root_tb.sv", 19},
    {1, 19, "rhs_use", "testdata/fixtures/interface_port_root/if_root_tb.sv", 21},
    {1, 19, "rhs_use", "testdata/fixtures/interface_port_root/if_root_tb.sv", 23},
    {1, 19, "rhs_use", "testdata/fixtures/interface_port_root/if_root_tb.sv", 19},
    {2, 11, "rhs_use", "testdata/fixtures/interface_port_root/if_root_tb.sv", 12},
    {2, 16, "control_use", "testdata/fixtures/interface_port_root/if_root_tb.sv", 21},
    {2, 16, "control_use", "testdata/fixtures/interface_port_root/if_root_tb.sv", 23},
    {2, 19, "rhs_use", "testdata/fixtures/interface_port_root/if_root_tb.sv", 21},
    {2, 19, "rhs_use", "testdata/fixtures/interface_port_root/if_root_tb.sv", 23},
    {3, 12, "rhs_use", "testdata/fixtures/interface_port_root/if_root_tb.sv", 13},
    {3, 16, "rhs_use", "testdata/fixtures/interface_port_root/if_root_tb.sv", 21},
    {3, 19, "rhs_use", "testdata/fixtures/interface_port_root/if_root_tb.sv", 21},
    {4, 13, "rhs_use", "testdata/fixtures/interface_port_root/if_root_tb.sv", 14},
    {4, 16, "rhs_use", "testdata/fixtures/interface_port_root/if_root_tb.sv", 23},
    {4, 19, "rhs_use", "testdata/fixtures/interface_port_root/if_root_tb.sv", 23},
    {5, 9, "rhs_use", "testdata/fixtures/interface_port_root/if_root_tb.sv", 30},
    {15, 19, "rhs_use", "testdata/fixtures/interface_port_root/if_root_tb.sv", 21},
    {15, 19, "rhs_use", "testdata/fixtures/interface_port_root/if_root_tb.sv", 23},
    {15, 19, "rhs_use", "testdata/fixtures/interface_port_root/if_root_tb.sv", 19},
    {16, 5, "rhs_use", "testdata/fixtures/interface_port_root/if_root_tb.sv", 36},
};
static const int kLoadCount = 28;
static const int kLoadStart[] = {0, 2, 12, 17, 20, 23, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 27, 28, 28, 28, 28};


extern "C" {

int xdd_abi_version(void) { return XDD_ABI_VERSION; }
uint64_t xdd_capabilities(void) {
    return XDD_CAP_SIGNAL_DIRECTION | XDD_CAP_PORT_CONNECTIONS
           | XDD_CAP_DRIVER_DEPENDENCY_ROLE | XDD_CAP_DRIVER_PREDICATE;
}

XddDb* xdd_init(void) { return reinterpret_cast<XddDb*>(1); }
void xdd_close(XddDb*) {}

int xdd_signal_count(XddDb*) { return kSignalCount; }

XddSignal xdd_resolve(XddDb*, const char* name) {
    int lo = 0, hi = kNameIndexCount - 1;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        int cmp = std::strcmp(name, kNameIndex[mid].name);
        if (cmp == 0) return kNameIndex[mid].index;
        if (cmp < 0) hi = mid - 1;
        else lo = mid + 1;
    }
    return -1;
}

const char* xdd_signal_name(XddDb*, int idx) {
    return (idx >= 0 && idx < kSignalCount) ? kSignals[idx].name : nullptr;
}
int xdd_signal_width(XddDb*, int idx) {
    return (idx >= 0 && idx < kSignalCount) ? kSignals[idx].width : 0;
}
const char* xdd_signal_type(XddDb*, int idx) {
    return (idx >= 0 && idx < kSignalCount) ? kSignals[idx].type : nullptr;
}
const char* xdd_signal_file(XddDb*, int idx) {
    return (idx >= 0 && idx < kSignalCount) ? kSignals[idx].file : nullptr;
}
int xdd_signal_line(XddDb*, int idx) {
    return (idx >= 0 && idx < kSignalCount) ? kSignals[idx].line : 0;
}
int xdd_signal_direction(XddDb*, int idx) {
    return (idx >= 0 && idx < kSignalCount) ? kSignalDirections[idx] : 0;
}

int xdd_port_connection_count(XddDb*, int idx) {
    if (idx < 0 || idx >= kSignalCount) return 0;
    int e = (idx + 1 < kSignalCount) ? kPortConnectionStart[idx + 1]
                                     : kPortConnectionCount;
    return e - kPortConnectionStart[idx];
}

void xdd_port_connection(XddDb*, int idx, int i,
                         int* connected_signal, const char** kind) {
    *connected_signal = -1;
    *kind = nullptr;
    if (idx < 0 || idx >= kSignalCount) return;
    int s = kPortConnectionStart[idx];
    int e = (idx + 1 < kSignalCount) ? kPortConnectionStart[idx + 1]
                                     : kPortConnectionCount;
    if (i < 0 || i >= (e - s)) return;
    const XddPortConnectionRec& connection = kPortConnections[s + i];
    *connected_signal = connection.connected_signal;
    *kind = connection.kind;
}

int xdd_trace_driver_count(XddDb*, int idx) {
    if (idx < 0 || idx >= kSignalCount) return 0;
    int e = (idx + 1 < kSignalCount) ? kDriverStart[idx + 1] : kDriverCount;
    return e - kDriverStart[idx];
}

void xdd_trace_driver(XddDb*, int idx, int i,
                      int* src_signal, const char** kind,
                      const char** file, int* line) {
    *src_signal = -1; *kind = nullptr; *file = nullptr; *line = 0;
    if (idx < 0 || idx >= kSignalCount) return;
    int s = kDriverStart[idx];
    int e = (idx + 1 < kSignalCount) ? kDriverStart[idx + 1] : kDriverCount;
    if (i < 0 || i >= (e - s)) return;
    const XddDriverRec& d = kDrivers[s + i];
    *src_signal = d.src_signal; *kind = d.kind; *file = d.file; *line = d.line;
}

const char* xdd_trace_driver_role(XddDb*, int idx, int i) {
    if (idx < 0 || idx >= kSignalCount) return nullptr;
    int s = kDriverStart[idx];
    int e = (idx + 1 < kSignalCount) ? kDriverStart[idx + 1] : kDriverCount;
    if (i < 0 || i >= (e - s)) return nullptr;
    return kDrivers[s + i].role;
}

const char* xdd_trace_driver_predicate(XddDb*, int idx, int i) {
    if (idx < 0 || idx >= kSignalCount) return nullptr;
    int s = kDriverStart[idx];
    int e = (idx + 1 < kSignalCount) ? kDriverStart[idx + 1] : kDriverCount;
    if (i < 0 || i >= (e - s)) return nullptr;
    return kDriverPredicates[s + i];
}

int xdd_trace_load_count(XddDb*, int idx) {
    if (idx < 0 || idx >= kSignalCount) return 0;
    int e = (idx + 1 < kSignalCount) ? kLoadStart[idx + 1] : kLoadCount;
    return e - kLoadStart[idx];
}

void xdd_trace_load(XddDb*, int idx, int i,
                    int* consumer, const char** kind,
                    const char** file, int* line) {
    *consumer = -1; *kind = nullptr; *file = nullptr; *line = 0;
    if (idx < 0 || idx >= kSignalCount) return;
    int s = kLoadStart[idx];
    int e = (idx + 1 < kSignalCount) ? kLoadStart[idx + 1] : kLoadCount;
    if (i < 0 || i >= (e - s)) return;
    const XddLoadRec& l = kLoads[s + i];
    *consumer = l.consumer; *kind = l.kind; *file = l.file; *line = l.line;
}

}  // extern "C"
