// Generated by Verilator --design-db. Do not edit.
#include "xdd_api.h"
#include <cstring>

static const XddSignalInfo kSignals[] = {
    {"top.clk", "port", 1, "xprop_top.sv", 12},
    {"top.reset", "port", 1, "xprop_top.sv", 13},
    {"top.out", "port", 8, "xprop_top.sv", 14},
    {"top.xprop_top.__vxrand___0", "wire", 8, "xprop_top.sv", 16},
    {"top.xprop_top.clk", "wire", 1, "xprop_top.sv", 12},
    {"top.xprop_top.reset", "wire", 1, "xprop_top.sv", 13},
    {"top.xprop_top.out", "wire", 8, "xprop_top.sv", 14},
    {"top.xprop_top.a", "wire", 8, "xprop_top.sv", 16},
    {"top.xprop_top.y", "wire", 8, "xprop_top.sv", 17},
    {"top.xprop_top.u_child.clk", "wire", 1, "xprop_top.sv", 2},
    {"top.xprop_top.u_child.a", "wire", 8, "xprop_top.sv", 3},
    {"top.xprop_top.u_child.y", "wire", 8, "xprop_top.sv", 4},
};
static const int kSignalCount = 12;

static const XddNameEntry kNameIndex[] = {
    {"top.clk", 0},
    {"top.out", 2},
    {"top.reset", 1},
    {"top.xprop_top.__vxrand___0", 3},
    {"top.xprop_top.a", 7},
    {"top.xprop_top.clk", 4},
    {"top.xprop_top.out", 6},
    {"top.xprop_top.reset", 5},
    {"top.xprop_top.u_child.a", 10},
    {"top.xprop_top.u_child.clk", 9},
    {"top.xprop_top.u_child.y", 11},
    {"top.xprop_top.y", 8},
};
static const int kNameIndexCount = 12;

static const XddDriverRec kDrivers[] = {
    {2, 8, "cont_assign", "xprop_top.sv", 19},
    {4, 0, "cont_assign", "xprop_top.sv", 12},
    {5, 1, "cont_assign", "xprop_top.sv", 13},
    {6, 2, "cont_assign", "xprop_top.sv", 14},
    {7, 3, "proc_assign", "xprop_top.sv", 16},
    {7, 1, "nba", "xprop_top.sv", 21},
    {8, 7, "nba", "xprop_top.sv", 7},
    {9, 0, "cont_assign", "xprop_top.sv", 2},
    {10, 7, "cont_assign", "xprop_top.sv", 3},
    {11, 8, "cont_assign", "xprop_top.sv", 4},
};
static const int kDriverCount = 10;
static const int kDriverStart[] = {0, 0, 0, 1, 1, 2, 3, 4, 6, 7, 8, 9};

static const XddLoadRec kLoads[] = {
    {0, 4, "rhs_use", "xprop_top.sv", 12},
    {0, 9, "rhs_use", "xprop_top.sv", 2},
    {1, 5, "rhs_use", "xprop_top.sv", 13},
    {1, 7, "rhs_use", "xprop_top.sv", 21},
    {2, 6, "rhs_use", "xprop_top.sv", 14},
    {3, 3, "rhs_use", "xprop_top.sv", 16},
    {3, 7, "rhs_use", "xprop_top.sv", 16},
    {7, 10, "rhs_use", "xprop_top.sv", 3},
    {7, 7, "rhs_use", "xprop_top.sv", 21},
    {7, 8, "rhs_use", "xprop_top.sv", 7},
    {8, 11, "rhs_use", "xprop_top.sv", 4},
    {8, 2, "rhs_use", "xprop_top.sv", 19},
};
static const int kLoadCount = 12;
static const int kLoadStart[] = {0, 2, 4, 5, 7, 7, 7, 7, 10, 12, 12, 12};


extern "C" {

XddDb* xdd_init(void) { return reinterpret_cast<XddDb*>(1); }
void xdd_close(XddDb*) {}

int xdd_signal_count(XddDb*) { return kSignalCount; }

XddSignal xdd_resolve(XddDb*, const char* name) {
    int lo = 0, hi = kNameIndexCount - 1;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        int cmp = std::strcmp(name, kNameIndex[mid].name);
        if (cmp == 0) return kNameIndex[mid].index;
        if (cmp < 0) hi = mid - 1;
        else lo = mid + 1;
    }
    return -1;
}

const char* xdd_signal_name(XddDb*, int idx) {
    return (idx >= 0 && idx < kSignalCount) ? kSignals[idx].name : nullptr;
}
int xdd_signal_width(XddDb*, int idx) {
    return (idx >= 0 && idx < kSignalCount) ? kSignals[idx].width : 0;
}
const char* xdd_signal_type(XddDb*, int idx) {
    return (idx >= 0 && idx < kSignalCount) ? kSignals[idx].type : nullptr;
}
const char* xdd_signal_file(XddDb*, int idx) {
    return (idx >= 0 && idx < kSignalCount) ? kSignals[idx].file : nullptr;
}
int xdd_signal_line(XddDb*, int idx) {
    return (idx >= 0 && idx < kSignalCount) ? kSignals[idx].line : 0;
}

int xdd_trace_driver_count(XddDb*, int idx) {
    if (idx < 0 || idx >= kSignalCount) return 0;
    int e = (idx + 1 < kSignalCount) ? kDriverStart[idx + 1] : kDriverCount;
    return e - kDriverStart[idx];
}

void xdd_trace_driver(XddDb*, int idx, int i,
                      int* src_signal, const char** kind,
                      const char** file, int* line) {
    *src_signal = -1; *kind = nullptr; *file = nullptr; *line = 0;
    if (idx < 0 || idx >= kSignalCount) return;
    int s = kDriverStart[idx];
    int e = (idx + 1 < kSignalCount) ? kDriverStart[idx + 1] : kDriverCount;
    if (i < 0 || i >= (e - s)) return;
    const XddDriverRec& d = kDrivers[s + i];
    *src_signal = d.src_signal; *kind = d.kind; *file = d.file; *line = d.line;
}

int xdd_trace_load_count(XddDb*, int idx) {
    if (idx < 0 || idx >= kSignalCount) return 0;
    int e = (idx + 1 < kSignalCount) ? kLoadStart[idx + 1] : kLoadCount;
    return e - kLoadStart[idx];
}

void xdd_trace_load(XddDb*, int idx, int i,
                    int* consumer, const char** kind,
                    const char** file, int* line) {
    *consumer = -1; *kind = nullptr; *file = nullptr; *line = 0;
    if (idx < 0 || idx >= kSignalCount) return;
    int s = kLoadStart[idx];
    int e = (idx + 1 < kSignalCount) ? kLoadStart[idx + 1] : kLoadCount;
    if (i < 0 || i >= (e - s)) return;
    const XddLoadRec& l = kLoads[s + i];
    *consumer = l.consumer; *kind = l.kind; *file = l.file; *line = l.line;
}

}  // extern "C"
