// Generated by Verilator --design-db. Do not edit.
#include "xdd_api.h"
#include <cstring>

static const XddSignalInfo kSignals[] = {
    {"top.clk", "port", 1, "xprop_top.sv", 12},
    {"top.reset", "port", 1, "xprop_top.sv", 13},
    {"top.out", "port", 8, "xprop_top.sv", 14},
    {"top.xprop_top.clk", "port", 1, "xprop_top.sv", 12},
    {"top.xprop_top.reset", "port", 1, "xprop_top.sv", 13},
    {"top.xprop_top.out", "port", 8, "xprop_top.sv", 14},
    {"top.xprop_top.a", "wire", 8, "xprop_top.sv", 16},
    {"top.xprop_top.y", "wire", 8, "xprop_top.sv", 17},
    {"top.xprop_top.u_child.clk", "port", 1, "xprop_top.sv", 2},
    {"top.xprop_top.u_child.a", "port", 8, "xprop_top.sv", 3},
    {"top.xprop_top.u_child.y", "port", 8, "xprop_top.sv", 4},
};
static const int kSignalCount = 11;

static const int kSignalDirections[] = {1, 1, 2, 1, 1, 2, 0, 0, 1, 1, 2};

static const XddNameEntry kNameIndex[] = {
    {"top.clk", 0},
    {"top.out", 2},
    {"top.reset", 1},
    {"top.xprop_top.a", 6},
    {"top.xprop_top.clk", 3},
    {"top.xprop_top.out", 5},
    {"top.xprop_top.reset", 4},
    {"top.xprop_top.u_child.a", 9},
    {"top.xprop_top.u_child.clk", 8},
    {"top.xprop_top.u_child.y", 10},
    {"top.xprop_top.y", 7},
};
static const int kNameIndexCount = 11;

static const XddDriverRec kDrivers[] = {
    {2, 7, "cont_assign", "xprop_top.sv", 19},
    {3, 0, "cont_assign", "xprop_top.sv", 12},
    {4, 1, "cont_assign", "xprop_top.sv", 13},
    {5, 2, "cont_assign", "xprop_top.sv", 14},
    {6, -1, "proc_assign", "xprop_top.sv", 16},
    {6, 1, "nba", "xprop_top.sv", 21},
    {7, 6, "nba", "xprop_top.sv", 7},
    {8, 0, "cont_assign", "xprop_top.sv", 2},
    {9, 6, "cont_assign", "xprop_top.sv", 3},
    {10, 7, "cont_assign", "xprop_top.sv", 4},
};
static const int kDriverCount = 10;
static const int kDriverStart[] = {0, 0, 0, 1, 2, 3, 4, 6, 7, 8, 9};

static const XddPortConnectionRec kPortConnections[] = {
    {0, 3, "port_boundary"},
    {0, 8, "port_boundary"},
    {1, 4, "port_boundary"},
    {2, 5, "port_boundary"},
    {2, 7, "port_boundary"},
    {3, 0, "port_boundary"},
    {4, 1, "port_boundary"},
    {5, 2, "port_boundary"},
    {8, 0, "port_boundary"},
    {9, 6, "port_boundary"},
    {10, 7, "port_boundary"},
};
static const int kPortConnectionCount = 11;
static const int kPortConnectionStart[] = {0, 2, 3, 5, 6, 7, 8, 8, 8, 9, 10};

static const XddLoadRec kLoads[] = {
    {0, 3, "rhs_use", "xprop_top.sv", 12},
    {0, 8, "rhs_use", "xprop_top.sv", 2},
    {1, 4, "rhs_use", "xprop_top.sv", 13},
    {1, 6, "rhs_use", "xprop_top.sv", 21},
    {2, 5, "rhs_use", "xprop_top.sv", 14},
    {6, 9, "rhs_use", "xprop_top.sv", 3},
    {6, 6, "rhs_use", "xprop_top.sv", 21},
    {6, 7, "rhs_use", "xprop_top.sv", 7},
    {7, 10, "rhs_use", "xprop_top.sv", 4},
    {7, 2, "rhs_use", "xprop_top.sv", 19},
};
static const int kLoadCount = 10;
static const int kLoadStart[] = {0, 2, 4, 5, 5, 5, 5, 8, 10, 10, 10};


extern "C" {

int xdd_abi_version(void) { return XDD_ABI_VERSION; }
uint64_t xdd_capabilities(void) {
    return XDD_CAP_SIGNAL_DIRECTION | XDD_CAP_PORT_CONNECTIONS;
}

XddDb* xdd_init(void) { return reinterpret_cast<XddDb*>(1); }
void xdd_close(XddDb*) {}

int xdd_signal_count(XddDb*) { return kSignalCount; }

XddSignal xdd_resolve(XddDb*, const char* name) {
    int lo = 0, hi = kNameIndexCount - 1;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        int cmp = std::strcmp(name, kNameIndex[mid].name);
        if (cmp == 0) return kNameIndex[mid].index;
        if (cmp < 0) hi = mid - 1;
        else lo = mid + 1;
    }
    return -1;
}

const char* xdd_signal_name(XddDb*, int idx) {
    return (idx >= 0 && idx < kSignalCount) ? kSignals[idx].name : nullptr;
}
int xdd_signal_width(XddDb*, int idx) {
    return (idx >= 0 && idx < kSignalCount) ? kSignals[idx].width : 0;
}
const char* xdd_signal_type(XddDb*, int idx) {
    return (idx >= 0 && idx < kSignalCount) ? kSignals[idx].type : nullptr;
}
const char* xdd_signal_file(XddDb*, int idx) {
    return (idx >= 0 && idx < kSignalCount) ? kSignals[idx].file : nullptr;
}
int xdd_signal_line(XddDb*, int idx) {
    return (idx >= 0 && idx < kSignalCount) ? kSignals[idx].line : 0;
}
int xdd_signal_direction(XddDb*, int idx) {
    return (idx >= 0 && idx < kSignalCount) ? kSignalDirections[idx] : 0;
}

int xdd_port_connection_count(XddDb*, int idx) {
    if (idx < 0 || idx >= kSignalCount) return 0;
    int e = (idx + 1 < kSignalCount) ? kPortConnectionStart[idx + 1]
                                     : kPortConnectionCount;
    return e - kPortConnectionStart[idx];
}

void xdd_port_connection(XddDb*, int idx, int i,
                         int* connected_signal, const char** kind) {
    *connected_signal = -1;
    *kind = nullptr;
    if (idx < 0 || idx >= kSignalCount) return;
    int s = kPortConnectionStart[idx];
    int e = (idx + 1 < kSignalCount) ? kPortConnectionStart[idx + 1]
                                     : kPortConnectionCount;
    if (i < 0 || i >= (e - s)) return;
    const XddPortConnectionRec& connection = kPortConnections[s + i];
    *connected_signal = connection.connected_signal;
    *kind = connection.kind;
}

int xdd_trace_driver_count(XddDb*, int idx) {
    if (idx < 0 || idx >= kSignalCount) return 0;
    int e = (idx + 1 < kSignalCount) ? kDriverStart[idx + 1] : kDriverCount;
    return e - kDriverStart[idx];
}

void xdd_trace_driver(XddDb*, int idx, int i,
                      int* src_signal, const char** kind,
                      const char** file, int* line) {
    *src_signal = -1; *kind = nullptr; *file = nullptr; *line = 0;
    if (idx < 0 || idx >= kSignalCount) return;
    int s = kDriverStart[idx];
    int e = (idx + 1 < kSignalCount) ? kDriverStart[idx + 1] : kDriverCount;
    if (i < 0 || i >= (e - s)) return;
    const XddDriverRec& d = kDrivers[s + i];
    *src_signal = d.src_signal; *kind = d.kind; *file = d.file; *line = d.line;
}

int xdd_trace_load_count(XddDb*, int idx) {
    if (idx < 0 || idx >= kSignalCount) return 0;
    int e = (idx + 1 < kSignalCount) ? kLoadStart[idx + 1] : kLoadCount;
    return e - kLoadStart[idx];
}

void xdd_trace_load(XddDb*, int idx, int i,
                    int* consumer, const char** kind,
                    const char** file, int* line) {
    *consumer = -1; *kind = nullptr; *file = nullptr; *line = 0;
    if (idx < 0 || idx >= kSignalCount) return;
    int s = kLoadStart[idx];
    int e = (idx + 1 < kSignalCount) ? kLoadStart[idx + 1] : kLoadCount;
    if (i < 0 || i >= (e - s)) return;
    const XddLoadRec& l = kLoads[s + i];
    *consumer = l.consumer; *kind = l.kind; *file = l.file; *line = l.line;
}

}  // extern "C"
