// Generated by Verilator --design-db. Do not edit.
#include "xdd_api.h"
#include <cstring>

static const XddSignalInfo kSignals[] = {
    {"top.clk", "port", 1, "stream_top.sv", 3},
    {"top.reset", "port", 1, "stream_top.sv", 4},
    {"top.in_valid", "port", 1, "stream_top.sv", 5},
    {"top.in_ready", "port", 1, "stream_top.sv", 6},
    {"top.in_data", "port", 8, "stream_top.sv", 7},
    {"top.out_valid", "port", 1, "stream_top.sv", 8},
    {"top.out_ready", "port", 1, "stream_top.sv", 9},
    {"top.out_data", "port", 8, "stream_top.sv", 10},
    {"top.stream_top.clk", "port", 1, "stream_top.sv", 3},
    {"top.stream_top.reset", "port", 1, "stream_top.sv", 4},
    {"top.stream_top.in_valid", "port", 1, "stream_top.sv", 5},
    {"top.stream_top.in_ready", "port", 1, "stream_top.sv", 6},
    {"top.stream_top.in_data", "port", 8, "stream_top.sv", 7},
    {"top.stream_top.out_valid", "port", 1, "stream_top.sv", 8},
    {"top.stream_top.out_ready", "port", 1, "stream_top.sv", 9},
    {"top.stream_top.out_data", "port", 8, "stream_top.sv", 10},
    {"top.stream_top.fifo", "wire", 8, "stream_top.sv", 12},
    {"top.stream_top.head", "wire", 2, "stream_top.sv", 13},
    {"top.stream_top.tail", "wire", 2, "stream_top.sv", 13},
    {"top.stream_top.count", "wire", 3, "stream_top.sv", 14},
    {"top.stream_top.full", "wire", 1, "stream_top.sv", 15},
    {"top.stream_top.empty", "wire", 1, "stream_top.sv", 16},
};
static const int kSignalCount = 22;

static const int kSignalDirections[] = {1, 1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 1, 2, 0, 0, 0, 0, 0, 0};

static const XddNameEntry kNameIndex[] = {
    {"top.clk", 0},
    {"top.in_data", 4},
    {"top.in_ready", 3},
    {"top.in_valid", 2},
    {"top.out_data", 7},
    {"top.out_ready", 6},
    {"top.out_valid", 5},
    {"top.reset", 1},
    {"top.stream_top.clk", 8},
    {"top.stream_top.count", 19},
    {"top.stream_top.empty", 21},
    {"top.stream_top.fifo", 16},
    {"top.stream_top.full", 20},
    {"top.stream_top.head", 17},
    {"top.stream_top.in_data", 12},
    {"top.stream_top.in_ready", 11},
    {"top.stream_top.in_valid", 10},
    {"top.stream_top.out_data", 15},
    {"top.stream_top.out_ready", 14},
    {"top.stream_top.out_valid", 13},
    {"top.stream_top.reset", 9},
    {"top.stream_top.tail", 18},
};
static const int kNameIndexCount = 22;

static const XddDriverRec kDrivers[] = {
    {3, 20, "cont_assign", "rhs", "stream_top.sv", 17},
    {5, 21, "cont_assign", "rhs", "stream_top.sv", 18},
    {7, 16, "cont_assign", "rhs", "stream_top.sv", 19},
    {7, 17, "cont_assign", "rhs", "stream_top.sv", 19},
    {8, 0, "cont_assign", "rhs", "stream_top.sv", 3},
    {9, 1, "cont_assign", "rhs", "stream_top.sv", 4},
    {10, 2, "cont_assign", "rhs", "stream_top.sv", 5},
    {11, 3, "cont_assign", "rhs", "stream_top.sv", 6},
    {12, 4, "cont_assign", "rhs", "stream_top.sv", 7},
    {13, 5, "cont_assign", "rhs", "stream_top.sv", 8},
    {14, 6, "cont_assign", "rhs", "stream_top.sv", 9},
    {15, 7, "cont_assign", "rhs", "stream_top.sv", 10},
    {17, 1, "nba", "control", "stream_top.sv", 22},
    {17, 5, "nba", "control", "stream_top.sv", 30},
    {17, 6, "nba", "control", "stream_top.sv", 30},
    {17, 1, "nba", "control", "stream_top.sv", 30},
    {18, 1, "nba", "control", "stream_top.sv", 22},
    {18, 4, "nba", "rhs", "stream_top.sv", 25},
    {18, 2, "nba", "control", "stream_top.sv", 25},
    {18, 3, "nba", "control", "stream_top.sv", 25},
    {18, 1, "nba", "control", "stream_top.sv", 25},
    {18, 2, "nba", "control", "stream_top.sv", 26},
    {18, 3, "nba", "control", "stream_top.sv", 26},
    {18, 1, "nba", "control", "stream_top.sv", 26},
    {19, 1, "nba", "control", "stream_top.sv", 22},
    {19, 2, "nba", "control", "stream_top.sv", 27},
    {19, 3, "nba", "control", "stream_top.sv", 27},
    {19, 1, "nba", "control", "stream_top.sv", 27},
    {19, 5, "nba", "control", "stream_top.sv", 31},
    {19, 6, "nba", "control", "stream_top.sv", 31},
    {19, 1, "nba", "control", "stream_top.sv", 31},
    {20, 19, "cont_assign", "rhs", "stream_top.sv", 15},
    {21, 19, "cont_assign", "rhs", "stream_top.sv", 16},
};
static const int kDriverCount = 33;
static const char* const kDriverPredicates[] = {
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "(top.reset)",
    "!(top.reset) && ((top.out_valid & top.out_ready))",
    "!(top.reset) && ((top.out_valid & top.out_ready))",
    "!(top.reset) && ((top.out_valid & top.out_ready))",
    "(top.reset)",
    "!(top.reset) && ((top.in_valid & top.in_ready))",
    "!(top.reset) && ((top.in_valid & top.in_ready))",
    "!(top.reset) && ((top.in_valid & top.in_ready))",
    "!(top.reset) && ((top.in_valid & top.in_ready))",
    "!(top.reset) && ((top.in_valid & top.in_ready))",
    "!(top.reset) && ((top.in_valid & top.in_ready))",
    "!(top.reset) && ((top.in_valid & top.in_ready))",
    "(top.reset)",
    "!(top.reset) && ((top.in_valid & top.in_ready))",
    "!(top.reset) && ((top.in_valid & top.in_ready))",
    "!(top.reset) && ((top.in_valid & top.in_ready))",
    "!(top.reset) && ((top.out_valid & top.out_ready))",
    "!(top.reset) && ((top.out_valid & top.out_ready))",
    "!(top.reset) && ((top.out_valid & top.out_ready))",
    "1",
    "1",
};
static const int kDriverStart[] = {0, 0, 0, 0, 1, 1, 2, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 12, 16, 24, 31, 32};

static const XddPortConnectionRec kPortConnections[] = {
    {0, 8, "port_boundary"},
    {1, 9, "port_boundary"},
    {2, 10, "port_boundary"},
    {3, 11, "port_boundary"},
    {3, 20, "port_boundary"},
    {4, 12, "port_boundary"},
    {5, 13, "port_boundary"},
    {5, 21, "port_boundary"},
    {6, 14, "port_boundary"},
    {7, 15, "port_boundary"},
    {7, 16, "port_boundary"},
    {7, 17, "port_boundary"},
    {8, 0, "port_boundary"},
    {9, 1, "port_boundary"},
    {10, 2, "port_boundary"},
    {11, 3, "port_boundary"},
    {12, 4, "port_boundary"},
    {13, 5, "port_boundary"},
    {14, 6, "port_boundary"},
    {15, 7, "port_boundary"},
};
static const int kPortConnectionCount = 20;
static const int kPortConnectionStart[] = {0, 1, 2, 3, 5, 6, 8, 9, 12, 13, 14, 15, 16, 17, 18, 19, 20, 20, 20, 20, 20, 20};

static const XddLoadRec kLoads[] = {
    {0, 8, "rhs_use", "stream_top.sv", 3},
    {1, 9, "rhs_use", "stream_top.sv", 4},
    {1, 17, "control_use", "stream_top.sv", 22},
    {1, 18, "control_use", "stream_top.sv", 22},
    {1, 19, "control_use", "stream_top.sv", 22},
    {1, 18, "control_use", "stream_top.sv", 25},
    {1, 18, "control_use", "stream_top.sv", 26},
    {1, 19, "control_use", "stream_top.sv", 27},
    {1, 17, "control_use", "stream_top.sv", 30},
    {1, 19, "control_use", "stream_top.sv", 31},
    {2, 10, "rhs_use", "stream_top.sv", 5},
    {2, 18, "control_use", "stream_top.sv", 25},
    {2, 18, "control_use", "stream_top.sv", 26},
    {2, 19, "control_use", "stream_top.sv", 27},
    {3, 11, "rhs_use", "stream_top.sv", 6},
    {3, 18, "control_use", "stream_top.sv", 25},
    {3, 18, "control_use", "stream_top.sv", 26},
    {3, 19, "control_use", "stream_top.sv", 27},
    {4, 12, "rhs_use", "stream_top.sv", 7},
    {4, 18, "rhs_use", "stream_top.sv", 25},
    {5, 13, "rhs_use", "stream_top.sv", 8},
    {5, 17, "control_use", "stream_top.sv", 30},
    {5, 19, "control_use", "stream_top.sv", 31},
    {6, 14, "rhs_use", "stream_top.sv", 9},
    {6, 17, "control_use", "stream_top.sv", 30},
    {6, 19, "control_use", "stream_top.sv", 31},
    {7, 15, "rhs_use", "stream_top.sv", 10},
    {16, 7, "rhs_use", "stream_top.sv", 19},
    {17, 7, "rhs_use", "stream_top.sv", 19},
    {17, 17, "rhs_use", "stream_top.sv", 30},
    {18, 18, "rhs_use", "stream_top.sv", 26},
    {19, 20, "rhs_use", "stream_top.sv", 15},
    {19, 21, "rhs_use", "stream_top.sv", 16},
    {19, 19, "rhs_use", "stream_top.sv", 27},
    {19, 19, "rhs_use", "stream_top.sv", 31},
    {20, 3, "rhs_use", "stream_top.sv", 17},
    {21, 5, "rhs_use", "stream_top.sv", 18},
};
static const int kLoadCount = 37;
static const int kLoadStart[] = {0, 1, 10, 14, 18, 20, 23, 26, 27, 27, 27, 27, 27, 27, 27, 27, 27, 28, 30, 31, 35, 36};


extern "C" {

int xdd_abi_version(void) { return XDD_ABI_VERSION; }
uint64_t xdd_capabilities(void) {
    return XDD_CAP_SIGNAL_DIRECTION | XDD_CAP_PORT_CONNECTIONS
           | XDD_CAP_DRIVER_DEPENDENCY_ROLE | XDD_CAP_DRIVER_PREDICATE;
}

XddDb* xdd_init(void) { return reinterpret_cast<XddDb*>(1); }
void xdd_close(XddDb*) {}

int xdd_signal_count(XddDb*) { return kSignalCount; }

XddSignal xdd_resolve(XddDb*, const char* name) {
    int lo = 0, hi = kNameIndexCount - 1;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        int cmp = std::strcmp(name, kNameIndex[mid].name);
        if (cmp == 0) return kNameIndex[mid].index;
        if (cmp < 0) hi = mid - 1;
        else lo = mid + 1;
    }
    return -1;
}

const char* xdd_signal_name(XddDb*, int idx) {
    return (idx >= 0 && idx < kSignalCount) ? kSignals[idx].name : nullptr;
}
int xdd_signal_width(XddDb*, int idx) {
    return (idx >= 0 && idx < kSignalCount) ? kSignals[idx].width : 0;
}
const char* xdd_signal_type(XddDb*, int idx) {
    return (idx >= 0 && idx < kSignalCount) ? kSignals[idx].type : nullptr;
}
const char* xdd_signal_file(XddDb*, int idx) {
    return (idx >= 0 && idx < kSignalCount) ? kSignals[idx].file : nullptr;
}
int xdd_signal_line(XddDb*, int idx) {
    return (idx >= 0 && idx < kSignalCount) ? kSignals[idx].line : 0;
}
int xdd_signal_direction(XddDb*, int idx) {
    return (idx >= 0 && idx < kSignalCount) ? kSignalDirections[idx] : 0;
}

int xdd_port_connection_count(XddDb*, int idx) {
    if (idx < 0 || idx >= kSignalCount) return 0;
    int e = (idx + 1 < kSignalCount) ? kPortConnectionStart[idx + 1]
                                     : kPortConnectionCount;
    return e - kPortConnectionStart[idx];
}

void xdd_port_connection(XddDb*, int idx, int i,
                         int* connected_signal, const char** kind) {
    *connected_signal = -1;
    *kind = nullptr;
    if (idx < 0 || idx >= kSignalCount) return;
    int s = kPortConnectionStart[idx];
    int e = (idx + 1 < kSignalCount) ? kPortConnectionStart[idx + 1]
                                     : kPortConnectionCount;
    if (i < 0 || i >= (e - s)) return;
    const XddPortConnectionRec& connection = kPortConnections[s + i];
    *connected_signal = connection.connected_signal;
    *kind = connection.kind;
}

int xdd_trace_driver_count(XddDb*, int idx) {
    if (idx < 0 || idx >= kSignalCount) return 0;
    int e = (idx + 1 < kSignalCount) ? kDriverStart[idx + 1] : kDriverCount;
    return e - kDriverStart[idx];
}

void xdd_trace_driver(XddDb*, int idx, int i,
                      int* src_signal, const char** kind,
                      const char** file, int* line) {
    *src_signal = -1; *kind = nullptr; *file = nullptr; *line = 0;
    if (idx < 0 || idx >= kSignalCount) return;
    int s = kDriverStart[idx];
    int e = (idx + 1 < kSignalCount) ? kDriverStart[idx + 1] : kDriverCount;
    if (i < 0 || i >= (e - s)) return;
    const XddDriverRec& d = kDrivers[s + i];
    *src_signal = d.src_signal; *kind = d.kind; *file = d.file; *line = d.line;
}

const char* xdd_trace_driver_role(XddDb*, int idx, int i) {
    if (idx < 0 || idx >= kSignalCount) return nullptr;
    int s = kDriverStart[idx];
    int e = (idx + 1 < kSignalCount) ? kDriverStart[idx + 1] : kDriverCount;
    if (i < 0 || i >= (e - s)) return nullptr;
    return kDrivers[s + i].role;
}

const char* xdd_trace_driver_predicate(XddDb*, int idx, int i) {
    if (idx < 0 || idx >= kSignalCount) return nullptr;
    int s = kDriverStart[idx];
    int e = (idx + 1 < kSignalCount) ? kDriverStart[idx + 1] : kDriverCount;
    if (i < 0 || i >= (e - s)) return nullptr;
    return kDriverPredicates[s + i];
}

int xdd_trace_load_count(XddDb*, int idx) {
    if (idx < 0 || idx >= kSignalCount) return 0;
    int e = (idx + 1 < kSignalCount) ? kLoadStart[idx + 1] : kLoadCount;
    return e - kLoadStart[idx];
}

void xdd_trace_load(XddDb*, int idx, int i,
                    int* consumer, const char** kind,
                    const char** file, int* line) {
    *consumer = -1; *kind = nullptr; *file = nullptr; *line = 0;
    if (idx < 0 || idx >= kSignalCount) return;
    int s = kLoadStart[idx];
    int e = (idx + 1 < kSignalCount) ? kLoadStart[idx + 1] : kLoadCount;
    if (i < 0 || i >= (e - s)) return;
    const XddLoadRec& l = kLoads[s + i];
    *consumer = l.consumer; *kind = l.kind; *file = l.file; *line = l.line;
}

}  // extern "C"
