// Generated by Verilator --design-db. Do not edit.
#include "xdd_api.h"
#include <cstring>

static const XddSignalInfo kSignals[] = {
    {"top.pclk", "port", 1, "apb_top.sv", 31},
    {"top.presetn", "port", 1, "apb_top.sv", 32},
    {"top.psel", "port", 1, "apb_top.sv", 33},
    {"top.penable", "port", 1, "apb_top.sv", 34},
    {"top.pwrite", "port", 1, "apb_top.sv", 35},
    {"top.paddr", "port", 8, "apb_top.sv", 36},
    {"top.pwdata", "port", 8, "apb_top.sv", 37},
    {"top.prdata", "port", 8, "apb_top.sv", 38},
    {"top.pready", "port", 1, "apb_top.sv", 39},
    {"top.pslverr", "port", 1, "apb_top.sv", 40},
    {"top.apb_top.pclk", "wire", 1, "apb_top.sv", 31},
    {"top.apb_top.presetn", "wire", 1, "apb_top.sv", 32},
    {"top.apb_top.psel", "wire", 1, "apb_top.sv", 33},
    {"top.apb_top.penable", "wire", 1, "apb_top.sv", 34},
    {"top.apb_top.pwrite", "wire", 1, "apb_top.sv", 35},
    {"top.apb_top.paddr", "wire", 8, "apb_top.sv", 36},
    {"top.apb_top.pwdata", "wire", 8, "apb_top.sv", 37},
    {"top.apb_top.prdata", "wire", 8, "apb_top.sv", 38},
    {"top.apb_top.pready", "wire", 1, "apb_top.sv", 39},
    {"top.apb_top.pslverr", "wire", 1, "apb_top.sv", 40},
    {"top.apb_top.u_slave.pclk", "wire", 1, "apb_top.sv", 3},
    {"top.apb_top.u_slave.presetn", "wire", 1, "apb_top.sv", 4},
    {"top.apb_top.u_slave.psel", "wire", 1, "apb_top.sv", 5},
    {"top.apb_top.u_slave.penable", "wire", 1, "apb_top.sv", 6},
    {"top.apb_top.u_slave.pwrite", "wire", 1, "apb_top.sv", 7},
    {"top.apb_top.u_slave.paddr", "wire", 8, "apb_top.sv", 8},
    {"top.apb_top.u_slave.pwdata", "wire", 8, "apb_top.sv", 9},
    {"top.apb_top.u_slave.prdata", "wire", 8, "apb_top.sv", 10},
    {"top.apb_top.u_slave.pready", "wire", 1, "apb_top.sv", 11},
    {"top.apb_top.u_slave.pslverr", "wire", 1, "apb_top.sv", 12},
    {"top.apb_top.u_slave.mem", "wire", 8, "apb_top.sv", 14},
};
static const int kSignalCount = 31;

static const XddNameEntry kNameIndex[] = {
    {"top.apb_top.paddr", 15},
    {"top.apb_top.pclk", 10},
    {"top.apb_top.penable", 13},
    {"top.apb_top.prdata", 17},
    {"top.apb_top.pready", 18},
    {"top.apb_top.presetn", 11},
    {"top.apb_top.psel", 12},
    {"top.apb_top.pslverr", 19},
    {"top.apb_top.pwdata", 16},
    {"top.apb_top.pwrite", 14},
    {"top.apb_top.u_slave.mem", 30},
    {"top.apb_top.u_slave.paddr", 25},
    {"top.apb_top.u_slave.pclk", 20},
    {"top.apb_top.u_slave.penable", 23},
    {"top.apb_top.u_slave.prdata", 27},
    {"top.apb_top.u_slave.pready", 28},
    {"top.apb_top.u_slave.presetn", 21},
    {"top.apb_top.u_slave.psel", 22},
    {"top.apb_top.u_slave.pslverr", 29},
    {"top.apb_top.u_slave.pwdata", 26},
    {"top.apb_top.u_slave.pwrite", 24},
    {"top.paddr", 5},
    {"top.pclk", 0},
    {"top.penable", 3},
    {"top.prdata", 7},
    {"top.pready", 8},
    {"top.presetn", 1},
    {"top.psel", 2},
    {"top.pslverr", 9},
    {"top.pwdata", 6},
    {"top.pwrite", 4},
};
static const int kNameIndexCount = 31;

static const XddDriverRec kDrivers[] = {
    {5, 6, "nba", "apb_top.sv", 23},
    {5, 2, "nba", "apb_top.sv", 23},
    {5, 3, "nba", "apb_top.sv", 23},
    {5, 4, "nba", "apb_top.sv", 23},
    {7, 30, "nba", "apb_top.sv", 25},
    {7, 5, "nba", "apb_top.sv", 25},
    {7, 2, "nba", "apb_top.sv", 25},
    {7, 3, "nba", "apb_top.sv", 25},
    {7, 4, "nba", "apb_top.sv", 25},
    {7, 1, "nba", "apb_top.sv", 20},
    {8, -1, "proc_assign", "apb_top.sv", 15},
    {9, -1, "proc_assign", "apb_top.sv", 16},
    {10, 0, "cont_assign", "apb_top.sv", 31},
    {11, 1, "cont_assign", "apb_top.sv", 32},
    {12, 2, "cont_assign", "apb_top.sv", 33},
    {13, 3, "cont_assign", "apb_top.sv", 34},
    {14, 4, "cont_assign", "apb_top.sv", 35},
    {15, 5, "cont_assign", "apb_top.sv", 36},
    {16, 6, "cont_assign", "apb_top.sv", 37},
    {17, 7, "cont_assign", "apb_top.sv", 38},
    {18, 8, "cont_assign", "apb_top.sv", 39},
    {19, 9, "cont_assign", "apb_top.sv", 40},
    {20, 0, "cont_assign", "apb_top.sv", 3},
    {21, 1, "cont_assign", "apb_top.sv", 4},
    {22, 2, "cont_assign", "apb_top.sv", 5},
    {23, 3, "cont_assign", "apb_top.sv", 6},
    {24, 4, "cont_assign", "apb_top.sv", 7},
    {25, 5, "cont_assign", "apb_top.sv", 8},
    {26, 6, "cont_assign", "apb_top.sv", 9},
    {27, 7, "cont_assign", "apb_top.sv", 10},
    {28, 8, "cont_assign", "apb_top.sv", 11},
    {29, 9, "cont_assign", "apb_top.sv", 12},
    {30, 1, "nba", "apb_top.sv", 19},
    {30, 1, "nba", "apb_top.sv", 19},
    {30, 1, "nba", "apb_top.sv", 19},
    {30, 1, "nba", "apb_top.sv", 19},
};
static const int kDriverCount = 36;
static const int kDriverStart[] = {0, 0, 0, 0, 0, 0, 4, 4, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32};

static const XddLoadRec kLoads[] = {
    {0, 10, "rhs_use", "apb_top.sv", 31},
    {0, 20, "rhs_use", "apb_top.sv", 3},
    {1, 11, "rhs_use", "apb_top.sv", 32},
    {1, 21, "rhs_use", "apb_top.sv", 4},
    {1, 30, "rhs_use", "apb_top.sv", 19},
    {1, 30, "rhs_use", "apb_top.sv", 19},
    {1, 30, "rhs_use", "apb_top.sv", 19},
    {1, 30, "rhs_use", "apb_top.sv", 19},
    {1, 7, "rhs_use", "apb_top.sv", 20},
    {2, 12, "rhs_use", "apb_top.sv", 33},
    {2, 22, "rhs_use", "apb_top.sv", 5},
    {2, 5, "rhs_use", "apb_top.sv", 23},
    {2, 7, "rhs_use", "apb_top.sv", 25},
    {3, 13, "rhs_use", "apb_top.sv", 34},
    {3, 23, "rhs_use", "apb_top.sv", 6},
    {3, 5, "rhs_use", "apb_top.sv", 23},
    {3, 7, "rhs_use", "apb_top.sv", 25},
    {4, 14, "rhs_use", "apb_top.sv", 35},
    {4, 24, "rhs_use", "apb_top.sv", 7},
    {4, 5, "rhs_use", "apb_top.sv", 23},
    {4, 7, "rhs_use", "apb_top.sv", 25},
    {5, 15, "rhs_use", "apb_top.sv", 36},
    {5, 25, "rhs_use", "apb_top.sv", 8},
    {5, 7, "rhs_use", "apb_top.sv", 25},
    {6, 16, "rhs_use", "apb_top.sv", 37},
    {6, 26, "rhs_use", "apb_top.sv", 9},
    {6, 5, "rhs_use", "apb_top.sv", 23},
    {7, 17, "rhs_use", "apb_top.sv", 38},
    {7, 27, "rhs_use", "apb_top.sv", 10},
    {8, 18, "rhs_use", "apb_top.sv", 39},
    {8, 28, "rhs_use", "apb_top.sv", 11},
    {9, 19, "rhs_use", "apb_top.sv", 40},
    {9, 29, "rhs_use", "apb_top.sv", 12},
    {30, 7, "rhs_use", "apb_top.sv", 25},
};
static const int kLoadCount = 34;
static const int kLoadStart[] = {0, 2, 9, 13, 17, 21, 24, 27, 29, 31, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33};


extern "C" {

XddDb* xdd_init(void) { return reinterpret_cast<XddDb*>(1); }
void xdd_close(XddDb*) {}

int xdd_signal_count(XddDb*) { return kSignalCount; }

XddSignal xdd_resolve(XddDb*, const char* name) {
    int lo = 0, hi = kNameIndexCount - 1;
    while (lo <= hi) {
        int mid = (lo + hi) / 2;
        int cmp = std::strcmp(name, kNameIndex[mid].name);
        if (cmp == 0) return kNameIndex[mid].index;
        if (cmp < 0) hi = mid - 1;
        else lo = mid + 1;
    }
    return -1;
}

const char* xdd_signal_name(XddDb*, int idx) {
    return (idx >= 0 && idx < kSignalCount) ? kSignals[idx].name : nullptr;
}
int xdd_signal_width(XddDb*, int idx) {
    return (idx >= 0 && idx < kSignalCount) ? kSignals[idx].width : 0;
}
const char* xdd_signal_type(XddDb*, int idx) {
    return (idx >= 0 && idx < kSignalCount) ? kSignals[idx].type : nullptr;
}
const char* xdd_signal_file(XddDb*, int idx) {
    return (idx >= 0 && idx < kSignalCount) ? kSignals[idx].file : nullptr;
}
int xdd_signal_line(XddDb*, int idx) {
    return (idx >= 0 && idx < kSignalCount) ? kSignals[idx].line : 0;
}

int xdd_trace_driver_count(XddDb*, int idx) {
    if (idx < 0 || idx >= kSignalCount) return 0;
    int e = (idx + 1 < kSignalCount) ? kDriverStart[idx + 1] : kDriverCount;
    return e - kDriverStart[idx];
}

void xdd_trace_driver(XddDb*, int idx, int i,
                      int* src_signal, const char** kind,
                      const char** file, int* line) {
    *src_signal = -1; *kind = nullptr; *file = nullptr; *line = 0;
    if (idx < 0 || idx >= kSignalCount) return;
    int s = kDriverStart[idx];
    int e = (idx + 1 < kSignalCount) ? kDriverStart[idx + 1] : kDriverCount;
    if (i < 0 || i >= (e - s)) return;
    const XddDriverRec& d = kDrivers[s + i];
    *src_signal = d.src_signal; *kind = d.kind; *file = d.file; *line = d.line;
}

int xdd_trace_load_count(XddDb*, int idx) {
    if (idx < 0 || idx >= kSignalCount) return 0;
    int e = (idx + 1 < kSignalCount) ? kLoadStart[idx + 1] : kLoadCount;
    return e - kLoadStart[idx];
}

void xdd_trace_load(XddDb*, int idx, int i,
                    int* consumer, const char** kind,
                    const char** file, int* line) {
    *consumer = -1; *kind = nullptr; *file = nullptr; *line = 0;
    if (idx < 0 || idx >= kSignalCount) return;
    int s = kLoadStart[idx];
    int e = (idx + 1 < kSignalCount) ? kLoadStart[idx + 1] : kLoadCount;
    if (i < 0 || i >= (e - s)) return;
    const XddLoadRec& l = kLoads[s + i];
    *consumer = l.consumer; *kind = l.kind; *file = l.file; *line = l.line;
}

}  // extern "C"
