ARG BASE_IMAGE
FROM ${BASE_IMAGE}
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    build-essential python3 perl zlib1g-dev liblz4-dev libatomic1 ca-certificates && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /work
CMD ["/bin/bash"]
